name: wasel
description: "Send anything, anywhere — fast and reliable delivery."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.12.3
  geolocator: ^10.0.0
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  geocoding: ^2.0.4
  location: ^5.0.0
  intl: ^0.19.0
  confetti: ^0.8.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  flutter_staggered_animations: ^1.0.1
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.5.0
  intl_phone_field: ^3.0.0
  country_code_picker: ^3.3.0 
  permission_handler: ^11.3.0
  flutter_animate: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

# ✅ flutter_launcher_icons: Must be at root level
flutter_launcher_icons:
  android: "launcher"
  ios: "launcher"
  image_path: "assets/images/logo.png"  # Should be 512x512 PNG

# ✅ Flutter assets and fonts
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/fonts/Cairo-Regular.ttf

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

# ✅ Fix google_api_headers warning
dependency_overrides:
  google_api_headers: ^1.5.0+1